config/routes.rb
Rails.application.routes.draw do

  get 'resumes/edit'

  resources :resumes, only: [:index, :new, :edit, :create, :destroy,  ]

  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'files' => 'resumes#index'
  get 'changes' => 'diff_viewer#index'

  get    'signup' => 'users#new'
  get    'login'  => 'sessions#new'
  get '/users/show'
  post 'login'  => 'sessions#create'
  get  'logout' => 'sessions#destroy'

  resources :users

end

app/models/resume.rb
class Resume < ActiveRecord::Base
  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
  validates :name, :attachment, :presence => true # Make sure name and attachment fields are present.
end

app/models/user.rb
class User < ActiveRecord::Base
    before_save { self.username = username.downcase }
    validates :username, presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/diff_viewer_controller.rb
class DiffViewerController < ApplicationController
  include DiffViewerHelper


  require 'diffy'

  def index
    # # @r = DiffViewer.new("FAKE_GIT")
    # s1 = File.read("FAKE_GIT/file.txt")
    # s2 = File.read("FAKE_GIT/file1.txt")
    # @d = Diffy::Diff.new(s1, s2).to_s(:html_simple)

    # @file = File.read("FAKE_GIT/file.txt")
    # @file1 = File.read("FAKE_GIT/file1.txt")

    @file = File.read("public/uploads/resume/attachment/string1.txt")
    @file1 = File.read("public/uploads/resume/attachment/string2.txt")

    @css = Diffy::CSS
    splitdiff = Diffy::SplitDiff.new(@file, @file1, :format => :html)

    @combined = Diffy::Diff.new(@file, @file1).to_s(:html_simple).html_safe
    @diffLeft = splitdiff.left.html_safe
    @diffRight = splitdiff.right.html_safe
  end

  def create
  end

  def destroy
  end
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  def index
    @resumes = Resume.all
  end

  def new
    @resume = Resume.new
  end

  def create
    @resume = Resume.new(resume_params)

    if @resume.save
      redirect_to resumes_path, notice: "The resume #{@resume.name} has been uploaded."
    else
      render "new"
    end
  end

  def destroy
    @resume = Resume.find(params[:id])
    @resume.destroy
    redirect_to resumes_path, notice:  "The resume #{@resume.name} has been deleted."
  end

  def edit
    @resume = Resume.new(resume_params)
  end


private
  def resume_params
    params.require(:resume).permit(:name, :attachment)
  end

def Download
  @resume = Resume.new
  # render text: "Hello World"


end




  #send_file(
    #"#{Rails.root}/public/uploads/resume/attachment/2/helloworld.txt",
    #filename: "helloworld.txt",
    #type: "application/txt"
    #)
    #send_file '/public/uploads/resume/attachment/2/helloworld.txt'
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(username: params[:session][:username].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
      # Log the user in and redirect to the user's show page.
    else
      flash.now[:danger] = "Invalid username/password combination"
      # Create an error message.
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
  @user = User.new(user_params)
  # @user = User.new(params[:user])
    if @user.save
      flash[:success] = "Thanks for signing up, #{@user.username}! You may now log in."
      redirect_to login_url
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diff_viewer_helper.rb
# known as the @r module, per app/controllers/diff_viewer_controller.rb
module DiffViewerHelper
    class DiffViewer


        # def initialize (repo)
        #     @g = Git.open(repo)
        # end

        # # pass these methods onwards to Git
        # def log
        #     @g.log
        # end

        # def show
        #     @g.show
        # end

        # # end passible functions

        # #-
        # def parseCommitDiff (from, to)
        #     @g.diff(from, to)
        # end

        # #-
        # def getFileContentForCommit (commit)
        #     oldHEAD = @g.commit  # record old state

        #     $g.checkout(commit)
        #     path = Dir.glob(@g.dir.path + "/file.*")[0]
        #     File.read(path)


        #     @g.checkout(oldHEAD)  # return to old state
        # end



    end
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    flash[:danger] = "You are now logged out."
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/diff_viewer/index.html.erb
<h1>DiffViewer</h1>

<!--<div class="diff-viewer">-->
<!--    <div class="form-group">-->
<!--        </%= form_tag do %>-->
<!--            </%= label_tag(:search, "Search for:") %>-->
<!--            </%= text_field_tag(:search) %>-->
<!--            </%= submit_tag("Search") %>-->
<!--        </% end %>-->
<!--    </div>-->

<dif class="row">
    <table>
        <div class="col-sm-6 well well-sm"><pre><%= @file %></pre></div>
        <div class="col-sm-6 well well-sm"><pre><%= @file1 %></pre></div>
        <div class="col-sm-6 well well-sm"><pre><%= @diffLeft %></pre></div>
        <div class="col-sm-6 well well-sm"><pre><%= @diffRight %></pre></div>
    </table>

    <div class="col-sm-12 well well-sm"><%= @combined %></div>
</dif>





    <!--<ul class="commit">-->
    <!--    </% @r.log.each do |commit| %>-->

    <!--    <li class="text-monospace">-->
    <!--        <span class="text-info"></%= commit %></span>-->
    <!--        <br><b>Message</b>: </%= commit.message %>-->
    <!--        <br><b>Date</b>: </%= commit.date.strftime("%m-%d-%y %H:%M:%S") %>-->
    <!--        <br><b>Author</b>: </%= commit.author.name %>-->
    <!--    </li>-->
    <!--    </% end %>-->
    <!--</ul>-->

    <!--<h2>Latest File</h2>-->
    <!--<pre></%=  %></pre>-->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HackISU App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha256-3dkvEK0WLHRJ7/Csr0BZjAWxERc5WH7bdeUya2aXxdU= sha512-+L4yy6FRcDGbXJ9mPG8MT/3UCDzwR9gPeyFNMCtInsol++5m3bk2bXWKdZjvybmohrAsn3Ua5x8gfLnbE1YkOg==" crossorigin="anonymous">

  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>

  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-7s5uDGW3AHqw6xtJmNNtr+OBRJUlgkNJEo78P4b0yRw= sha512-nNo+yCHEyn0smMxSswnf/OnX6/KwJuZTlNZBjauKhTK0c+zT+q5JOCx0UFhXQ6rJR9jg6Es8gPuD2uZcYDLqSw==" crossorigin="anonymous">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha256-KXn5puMvxCw+dAYznun+drMdG1IFl3agK0p/pqT9KAo= sha512-2e8qq0ETcfWRI4HJBzQiA3UoyFk6tbNyG+qSaIBZLyW9Xf3sWZHN/lxe9fTh1U45DpPf07yj94KsUHHWe4Yk1A==" crossorigin="anonymous"></script>

  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">

      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <div class="navbar-header">
          <!--Our Logo-->
          <a class="navbar-brand" href="http://hackisu.com">
            <span id="logo-icon" class="fa-stack">
              <i class="fa fa-square fa-stack-2x"></i>
              <i class="fa fa-terminal fa-stack-1x fa-inverse"></i>
            </span>
            <span id="logo">HackISU</span>
          </a>
          <!--/Logo-->
        </div>
      <div>
        <ul class="nav navbar-nav navbar-left">
          <li><%= link_to "Home", root_url %></li>
          <li><%= link_to "About/Help", help_url %></li>
          <li><%= link_to "Upload File", files_url %></li>
          <li><%= link_to "See Changes", changes_url %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", '#' %></li>
                  <li class="divider"></li>
                  <li><%= link_to "Log Out", logout_path %></li>
                </ul> <!-- /.dropdown-menu-->
              </li> <!-- /.dropdown-->
            <% else %>
              <li><%= link_to "Log In", login_url %></li>
              <li><%= link_to "Sign Up", "/users/new" %></li>
            <% end %> <!-- logged_in -->
          </ul>
        </div><!--/.nav-collapse -->
    </div><!-- /.container -->
  </nav>
  <div class="container">
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/layouts/header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>

            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/resumes/create.html.erb
<h1>Resumes#create</h1>
<p>Find me in app/views/resumes/create.html.erb</p>

app/views/resumes/destroy.html.erb
<h1>Resumes#destroy</h1>
<p>Find me in app/views/resumes/destroy.html.erb</p>

app/views/resumes/edit.html.erb
<% if !@resume.errors.empty? %>
  <div class="alert alert-error">
    <ul>
      <% @resume.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="well">
  <%= form_for @resume, html: { multipart: true } do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :attachment %>
    <%= f.file_field :attachment %>
    <%= f.submit "Save", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/resumes/index.html.erb
<% if !flash[:notice].blank? %>
  <div class="alert alert-info">
  <%= flash[:notice] %>
  </div>
<% end %>
<br />
<%= link_to "Upload file", new_resume_path, class: "btn btn-primary" %>

<br />
<br />
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <!--<th>Download Link</th>-->
      <th>FileName</th>
      <th>Delete</th>
    </tr>
  </thead>
  <tbody>
    <% @resumes.each do |resume| %>
      <tr>
        <td><%= resume.name %></td>
        <!--<td></%= link_to "Download Resume", resume.attachment_url %></td>-->
        <td><%= link_to File.basename(resume.attachment_url), resume.attachment_url %></td>

        <td><%= button_to "Delete",  resume, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{resume.name}?" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/resumes/new.html.erb
<% if !@resume.errors.empty? %>
  <div class="alert alert-error">
    <ul>
      <% @resume.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="well">
  <%= form_for @resume, html: { multipart: true } do |f| %>
    <%= f.label :Name %>
   
    <%= f.text_field :name %>
    <%= f.label :attachment %>
    <%= f.file_field :attachment %>
    <%= f.submit "Save", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/help.html.erb
<h1>About</h1>
<p style="font-size:160%;">Welcome to our web app! This is our project for HackISU 2016.
In this project we used a web application framework, Ruby on Rails, to create an online web app.
The intended purpose of this web project to create a web app where users can share, upload, and
reupload text files while keeping all previous revisions. Due to the time constraint we did not
have enough time to complete the web app.</p>

<h1>Help</h1>
<p style="font-size:160%;">In order to use this web app, first upload two text files in the "Upload File" tab.
When uploading files make sure to only upload files named "string1.txt" and "string2.txt". Then
go to the "See Changes" tab to view the differences between the two files. Users can also create a their own
personal profiles.</p>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
<html>
    <html lang="en-US">
    <head>
        <title>Home Page</title>
    </head>
    <body>
        <br><br><br><br><br>
        <h1 style="text-align:center; color:darkred;">HackISU 2016</h1>
        <p style="color:white; text-align:center;"><b>Welcome to our website!!!</p>
        <hr>

        <p style="text-align:center;"><%= image_tag("hackathonlogo2.png", :alt => "HackISU 2016", :width => "400", :height => "400") %></p>
        <!--<p style="text-align:center;"><img src="/app/assets/images/hackathonlogo2.png" alt="HackISU 2016" width="400" height="400"></p>-->

        <p>© <%= Date.today.year %> Cole, George, Layton, Victory.</p>
    </body>
</html>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>
<h1>Sign Up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% if logged_in? %>
    <h1 style="text-align:center;">You are now logged in, <u><%= @user.username %></u>!</h1>
    <br>
<% else %>
    <div class="alert alert-danger"><strong>ERROR</strong>: You are not logged in.</div>
<% end %>